DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS baskets CASCADE;
DROP TABLE IF EXISTS basketItems;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS orderItems;
DROP DOMAIN IF EXISTS st;
DROP TABLE IF EXISTS orderStatus;